### ISSUE TITLE
test coverage

### ISSUE THREAD

**Issue by amtoine** [amtoine/nu-git-manager#24]
in the long run, i think we need unit and integration tests, as much as possible :+1: 

- [x] a CI to run them all: https://github.com/amtoine/nu-git-manager/pull/27
- [x] unit tests: all the internals are tested
    - https://github.com/amtoine/nu-git-manager/pull/26
    - https://github.com/amtoine/nu-git-manager/pull/29
    - https://github.com/amtoine/nu-git-manager/pull/39
    - https://github.com/amtoine/nu-git-manager/pull/34
    - https://github.com/amtoine/nu-git-manager/pull/44
- [x] integration / end-to-end tests: make sure the `gm` commands work as expected with real repos
    - https://github.com/amtoine/nu-git-manager/pull/48
- [ ] cover the modules of `nu-git-manager-sugar`
    - `git-prompt`
        - https://github.com/amtoine/nu-git-manager/pull/121
        - https://github.com/amtoine/nu-git-manager/pull/122

**Comment by amtoine** [comment]
i updated this issue's tasks to reflect the fact that we need tests for the `gm` commands themselves, e.g. these kind of tests would help catch bugs like the one with `$env.GIT_REPOS_CACHE = /tmp/repos.cache` in https://github.com/amtoine/nu-git-manager/pull/39, see the PR for more details :wink:

**Comment by amtoine** [comment]
> What is the link between the two? Sorry I don't see it.
>
> > _Originally posted by @melMass in https://github.com/amtoine/nu-git-manager/issues/44#issuecomment-1783598605_
>
answering you here directly :relieved: 

the idea behind #44 was that there was cache-related logic *hardcoded* inside the `gm` commands themselves.
however because we do not test these commands directly, only the internals of the *`nu-git-manager` library*, a bug with the cache was hidden... and then addressed in https://github.com/amtoine/nu-git-manager/pull/39 by not assuming the extension of user-defined caches is always `.nuon` :+1: 

i managed to move this logic to the library out of the public API and the `gm` commands :partying_face: 

the question is:
- do we keep these tests only and thus close this PR because basically everything is covered now i think?
- do we write true *integration tests* for the `gm` commands and thus leave this PR open?

such tests could look like
```nushell
gm clone https://github.com/amtoine/nu-git-manager
assert equal (gm list) ["amtoine/nu-git-manager"]
```
that kind of stuff :yum:

**Comment by melMass** [comment]
I would vote for merging this and do a separate PR for testing public commands, I think it makes sense to have test for these too

**Comment by amtoine** [comment]
> I would vote for merging this and do a separate PR for testing public commands, I think it makes sense to have test for these too
>
i've updated the issue description accordingly => integration / end-to-end tests still need to be addressed :blush:
