### ISSUE TITLE
improve getting started in the readme

### ISSUE THREAD

**Issue by melMass** [amtoine/nu-git-manager#25]
Just dumping that here, as not everyone keep track of nushell version I think there should be a requirement section on the readme (could also be used to list other dependencies, like `gh (optional)`.

Since a recent commit gm doesn't work on 0.79.1:

![image](https://github.com/amtoine/nu-git-manager/assets/7041726/6f7b3f0d-afcc-47e3-8b1b-10eb94d0e961)

So I think it should also specify `nushell 0.8.0+`

**Comment by melMass** [comment]
I actually still have issues after updating to latest main (this is on mac)🤔 
<img width="825" alt="image" src="https://github.com/amtoine/nu-git-manager/assets/7041726/a2ee8487-5111-4133-9b43-fef7189de938">

**Comment by amtoine** [comment]
@melMass 
do bbdf01e88df1880c3382a7d30b1ba88fc66092a2 and 98c0bd9bf11ab4e3e9831fbbbb7afb9d9ef7f7b3 fix both these issues? :yum:

**Comment by amtoine** [comment]
at least i think the errors are gone now with latest Nushell and latest `nu-git-manager` :relieved:

**Comment by melMass** [comment]
Indeed! Thanks 🙏

**Comment by amtoine** [comment]
> Indeed! Thanks pray
>
grrrreat :yum:
