### ISSUE TITLE
a bit of design: namespace and imports

### ISSUE THREAD

**Issue by amtoine** [amtoine/nu-git-manager#28]
i've been thinking a bit about the user experience of `nu-git-manager`.
with https://github.com/amtoine/nu-git-manager/pull/26, i feel the command API is quite good and simple (:crossed_fingers:)

however, here i would like to talk about the way the library definitions are imported :yum:

cc/ @melMass 

## the namespace
i think all the commands from `nu-git-manager` should be subcommands of `gm`, to have
- a single namespace
- not clashing with external commands such as `git` or `gh` which can break external completers

## imports
here is what i propose, the implementation is really a detail in the scope of this issue :ok_hand:
- main commands
```nushell
use nu-git-manager main [gm, "gm list", "gm clone", ...]
use nu-git-manager main *
```
- Git commands from sugar
```nushell
use nu-git-manager sugar git ["gm branch", "gm fetch", ...]
use nu-git-manager sugar git *
```
- Github commands from sugar
```nushell
use nu-git-manager sugar gh ["gm pr checkout", ...]
use nu-git-manager sugar gh *
```
- all of sugar?
```nushell
# would import all `gm branch`, `gm fetch`, `gm pr checkout`, ..., without `sugar` as prefix
use nu-git-manager sugar *
```
- everything?
```nushell
# would import all `gm clone`, `gm pr checkout`, ..., without `sugar` nor `main` as prefixes
use nu-git-manager *
```

**Comment by amtoine** [comment]
i was thinking about what we could do with the new https://github.com/nushell/nupm/pull/33 and https://github.com/nushell/nupm/pull/35 :smirk: 

as you can see in https://github.com/nushell/nu_scripts/pull/650 and https://github.com/nushell/nu_scripts/pull/648, we could have two directories
- `./src/nu-git-manager/`
- `./src/nu-git-manager-sugar/`

this would allow to install and use the main `gm` command on one side and the other optional ones from a separate module:
```nushell
use nu-git-manager "gm clone"
use nu-git-manager-sugar git *  # would import `git branches` and friends


what do you think? :yum:

**Comment by melMass** [comment]
Shouldn't we move that to discussions? I wanted to open a thread or a project to list things we talked about "privately" since I think we can pick up old ideas now that there is a good base

**Comment by melMass** [comment]
> i was thinking about what we could do with the new [nushell/nupm#33](https://github.com/nushell/nupm/pull/33) and [nushell/nupm#35](https://github.com/nushell/nupm/pull/35) 😏

Nice I will read up all that, I did not understand much about nupm for now, mainly its cli hasn't any documentation? (maybe I did not install it well, I only needed it for running the gm tests and it worked fine)

**Comment by amtoine** [comment]
> Shouldn't we move that to discussions? I wanted to open a thread or a project to list things we talked about "privately" since I think we can pick up old ideas now that there is a good base
>
i wouldn't mind :yum:

**Comment by amtoine** [comment]
> Nice I will read up all that, I did not understand much about nupm for now, mainly its cli hasn't any documentation? (maybe I did not install it well, I only needed it for running the gm tests and it worked fine)
>
i might give a short demo of Nupm tonight during the core-team meeting, feel free to join :wink: 

the only thing you'd need to do, and it's the same currently, is to run
```nushell
use nupm
nupm install --force --path /path/to/nu-git-manager
```
currently, that would install `nu-git-manager` as a single module.
what i propose above would install two modules, `nu-git-manager` and `nu-git-manager-sugar` :+1:
