### ISSUE TITLE
cannot clone *Suckless* software

### ISSUE THREAD

**Issue by amtoine** [amtoine/nu-git-manager#32]
## description
`nu-git-manager` is not able to clone [*Suckless* software](https://suckless.org/).

## reproduce
```nushell
> gm clone git://git.suckless.org/st
Cloning into '/home/amtoine/documents/repos/git.suckless.org/st/st'...
fatal: repository 'https://git.suckless.org/st/st/' not found
```

## expected
i would like to be able to do something like
```nushell
> gm clone git://git.suckless.org/st --fetch git --push git
```
to specify to use the GIT protocol to at least fetch, you probably won't push there.

**Comment by amtoine** [comment]
i already have a fix for this actually in the [`support-suckless-host` branch](https://github.com/amtoine/nu-git-manager/tree/support-suckless-host) :smirk: :ok_hand:

**Comment by melMass** [comment]
What is the git protocol 🤔?

**Comment by amtoine** [comment]
> What is the git protocol 🤔?
>
no idea :laughing: 

it's the Nushell *scheme* used by the *Suckless* pieces of software [^git]


[^git]: see https://git.suckless.org/st/log.html
