### ISSUE TITLE
add a command to get the version of `nu-git-manager`

### ISSUE THREAD

**Issue by amtoine** [amtoine/nu-git-manager#57]
related to
- https://github.com/nushell/nupm/pull/43

## Description
i would like to
- [ ] add a `gm version` command when it gets possible 
- [ ] add a stronger dependency on Nupm in `package.nuon`

**Comment by amtoine** [comment]
> What is "add a stronger dependency on Nupm in package.nuon"?
>
since #50, we need nushell/nupm#33.

using any version of Nupm prior to commit f428826 would end up failing the install of the latest `main` of `nu-git-manager`.

i guess we could say that in the README or `package.nuon`: that's what i called *stronger dependency* :yum:

**Comment by melMass** [comment]
> or package.nuon

That be ideal, same for min nushell version, is this already a thing?

**Comment by amtoine** [comment]
> That be ideal, same for min nushell version, is this already a thing?
>
not that i'm aware of :thinking: 

i guess Nupm could check a few more things before installing a package in the future, e.g. dependencies :smirk:

**Comment by texastoland** [comment]
Closed by #182.
