### ISSUE TITLE
should we include `git` related prompts?

### ISSUE THREAD

**Issue by amtoine** [amtoine/nu-git-manager#9]
really just a question :relieved:

**Comment by melMass** [comment]
I guess it wouldn't hurt, what do you have in mind?

Maybe composable utilities to build your own with a few presets? 
Ideally it would integrate with other prompts

**Comment by amtoine** [comment]
> I guess it wouldn't hurt, what do you have in mind?
> 
not precisely, i see there are a few things in the `nushell/nu_scripts` but i do not use them :thinking: 
there will be investigation required for this :yum: 

> Maybe composable utilities to build your own with a few presets? Ideally it would integrate with other prompts
>
:+1:
